mysql:
  image: mysql:5.7
  environment:
    - MYSQL_DATABASE=HttpRunner
    - MYSQL_ROOT_PASSWORD=1qaz@WSX
  volumes:
    - ./mysql_data:/var/lib/mysql
  ports:
    - "3306:3306"
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"

web:
  build: .
  ports:
    - "8000:8000"
    - "5555:5555"
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
  volumes: 
    - ./HttpRunnerManager:/code
  command: 
        - /bin/sh
        - -c
        - |
          nohup python manage.py celery -A HttpRunnerManager worker --loglevel=info &
          nohup python manage.py celery beat --loglevel=info &
          nohup celery flower &
          python manage.py runserver 0.0.0.0:8000
